### ISSUE TITLE
UI color does not stay, reverts to default after update

### ISSUE THREAD

**Issue by jeffdupont** [atom-material/atom-material-ui#390] opened 2017-05-05 21:07 UTC
1.3.10

I have set the theme to use the predefined colors "Blue". After package update, color returns to "Teal". Value in the settings remains set to "Blue" and the Primary color show the correct blue set.

**Comment by silvestreh** [comment] 2017-05-06 01:52
Looks like you have a dupe of #243 on your hands. If you're willing to update to Atom 1.17-beta, you can also update to Material UI 2.0 where this should be fixed.

**Closed by silvestreh** 2017-05-06 01:52 UTC
