### ISSUE TITLE
Background color renders badly with dark syntax themes

### ISSUE THREAD

**Issue by Je4hel** [atom-material/atom-material-ui#335] opened 2016-10-15 14:03 UTC
Background color for dark syntax themes renders incorrectly.

**Reproduction Steps:**
1. Use the Material UI theme
2. Use a dark syntax theme (Material, Atom Dark, base 16 dark...)
3. Open a file an type some text

**Expected behavior:**

Background color should render on the whole background

**Observed behavior:**

Background is rendered with different color rectangles that move when the cursor moves to different lines.

**Screenshots and GIFs**

![sans titre](https://cloud.githubusercontent.com/assets/5781642/19410600/7b9912a4-92f0-11e6-9b74-e5cc158437ef.jpeg)

**Atom version:** 1.11.1
**OS and version:** macOS Sierra

**Installed packages:**
- activate-powermode
- atom-terminal

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: Yes
- Problem happens with all files and projects, not only some files or projects: Yes

I am not a hundred percent sure it is because of Material UI but I think it is, as it happens with several syntax themes. The problem is not reproduced with light themes.

**Comment by arussellsaw** [comment] 2016-10-28 10:44
the issue is present in light themes, just less visible

tilt your screen if you cannot see it, it's very faint.
![screen shot 2016-10-28 at 11 43 40](https://cloud.githubusercontent.com/assets/5236823/19804025/d3438698-9d03-11e6-8ae4-c76276d6c01c.png)

**Comment by schrej** [comment] 2016-10-28 10:51
This is not an issue of this theme, it isn't even a atom problem, it's a rendering issue with electron (there is an atom issue where they explained it). Some future atom update will fix it.
In the meantime start atom with `--disable-gpu` for correct rendering.

**Comment by justinschier** [comment] 2016-11-05 16:34
I'm having the same issue in 1.11.2 in macOS Sierra when using Atom Material theme and Atom Material Dark as the syntax theme. It flashes when I just move my mouse around.

![image](https://cloud.githubusercontent.com/assets/126453/20031818/201f838a-a354-11e6-802e-9acb3eaf0dbb.png)

**Comment by schrej** [comment] 2016-11-05 17:50
@justinschier did you read my message above?

**Comment by silvestreh** [comment] 2016-11-27 00:23
I'll close this since it's not related to the theme and the answer was shared by @schrej (thank you for enlightening us!)

**Closed by silvestreh** 2016-11-27 00:23 UTC

**Comment by montanaflynn** [comment] 2017-05-17 18:32
Any update on this? It's now May 2017 and I just upgraded to Sierra and now this is happening. 

I even tried starting atom with `--disable-gpu` as suggested and that made no difference.

<img width="1071" alt="screen shot 2017-05-17 at 11 31 39 am" src="https://cloud.githubusercontent.com/assets/24260/26169967/7d9d2156-3af4-11e7-9dd9-d2ec4031648d.png">

**Comment by montanaflynn** [comment] 2017-05-17 18:37
Here's an open issue on the main atom repo that has more updates. They actually suggest using the flag ` atom --enable-gpu-rasterization` but that didn't work for me on my external display.

`https://github.com/atom/atom/issues/12634`

**Comment by silvestreh** [comment] 2017-05-17 18:54
@montanaflynn it's technically not an issue with the theme, but with Electron

**Comment by stefanocampos** [comment] 2018-07-20 02:01
I solved this problem by going into settings > Core settings > Color Profile > choose ¨Use sRGB color profile¨ instead of ¨Use color profile configured in the operating system¨.

Also, there is another way that shall work. Go to Ubuntu Settings (if you are using Ubuntu) > Devices > Color > and disable ¨Laptop screen¨ profile. 

Both ways worked just great for me. Hope this helps.

**Comment by deviantony** [comment] 2018-08-21 18:39
@stefanocampos thanks for sharing this ! Was having the same issue with Atom 1.29.

**Comment by chrisk8er** [comment] 2018-10-15 02:28
@stefanocampos thanks, work perfectly...
